# Generated by Django 3.2.7 on 2021-09-21 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=32.32)),
                ('longitude', models.FloatField(default=33.33)),
                ('collection_frequency', models.IntegerField(default=1)),
                ('last_collection', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='collect', max_length=20)),
                ('bin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='binoperations.bin')),
            ],
        ),
    ]
